site_name: Cakebox Documentation

site_description: Documentation for the Cakebox project.

dev_addr: 0.0.0.0:8000

docs_dir: sources

include_search: true

theme: readthedocs


pages:

# Home:
- ['index.md', 'Home']

# Getting Started:
- ['installation.md', '', 'Getting Started']

# Configuration:
- ['configuration.md', '', 'Configuration']

# Usage:
- ['usage.md', '', 'Usage']

# Additional Information:
- ['additional/ssh-windows.md', 'Additional Information', 'SSH on Windows']
- ['additional/known-limitations.md', 'Additional Information', 'Known Limitations']
